theme: minima
title: Recipes
description: Recipe site with Schema.org descriptions
show_downloads: false
collections:
  recipes:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
