theme: jekyll-theme-time-machine
title: Recipes
description: Recipe site with Schema.org descriptions
show_downloads: false
collections:
  recipes:
    output: true
    permalink: /recipes/:name

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
